app:
  app_name: GatewayService
  debug: false
  host: 0.0.0.0
  port: 8080
  logging:
    logger_name: GatewayServiceLogger
    app_name: GatewayService
    level: info
    file: gateway_service.log
    file_level: info

tokens:
  jwks_uri: http://dev-52601744.okta.com/oauth2/default/v1/keys
  issuer: https://dev-52601744.okta.com/oauth2/default
  audience: api://default

rating_service:
  host: 0.0.0.0
  port: 8050

library_service:
  host: 0.0.0.0
  port: 8060

reservation_service:
  host: 0.0.0.0
  port: 8070

circuit_breaker:
  failure_threshold: 10
  knock_timeout: 30   # опрашивать упавшие сервисы раз в N секунд