app:
  app_name: RatingService
  debug: false
  host: 0.0.0.0
  port: 8050
  logging:
    logger_name: RatingServiceLogger
    app_name: RatingService
    level: info
    file: rating_service.log
    file_level: info

database:
  connector: postgres
  dbname: ratings
  username: program
  password: test
  host: 0.0.0.0
  port: 5432
  logging:
    logger_name: DatabaseLogger
    app_name: RatingService
    level: info
    file: rating_service.log
    file_level: info
