app:
  app_name: RatingService
  debug: false
  host: 0.0.0.0
  port: 8050
  logging:
    logger_name: RatingServiceLogger
    app_name: RatingService
    level: info
    file: rating_service.log
    file_level: info

tokens:
  jwks_uri: http://dev-52601744.okta.com/oauth2/default/v1/keys
  issuer: https://dev-52601744.okta.com/oauth2/default
  audience: api://default

database:
  connector: postgres
  dbname: ratings
  username: program
  password: test
  host: 0.0.0.0
  port: 5432
  logging:
    logger_name: DatabaseLogger
    app_name: RatingService
    level: info
    file: rating_service.log
    file_level: info
