name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]

env:
  KUBER_HOST: ${{ secrets.KUBER_HOST }}
  KUBER_TOKEN: ${{ secrets.KUBER_TOKEN }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Build and publish images
#        timeout-minutes: 15
#        run: |
#          cd src
#          chmod +x build_docker.sh
#          ./build_docker.sh
#
#      - name: Deploy
#        run: |
#          set -x
#          kubectl config set-cluster rsoi --server="$KUBER_HOST" --insecure-skip-tls-verify=true
#          kubectl config set-credentials cloud_okteto_com-user --token="$KUBER_TOKEN"
#          kubectl config set-context default --cluster=rsoi --user=cloud_okteto_com-user --namespace="kurush7"
#          kubectl config use-context default
#
#          kubectl get pods
#          cd k8s
#          helm upgrade services ./services-chart
#          sleep 45

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"